# Generated by Django 4.0.3 on 2022-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('service', models.CharField(max_length=3)),
                ('details', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
