# Generated by Django 4.0.3 on 2022-09-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=10)),
                ('c_content', models.TextField(max_length=80)),
                ('c_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=10)),
                ('p_content', models.TextField(max_length=80)),
                ('p_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=10)),
                ('s_content', models.TextField(max_length=80)),
                ('s_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='year_of_service',
            fields=[
                ('y_id', models.IntegerField(primary_key=True, serialize=False)),
                ('y_name', models.CharField(max_length=10)),
                ('y_content', models.TextField(max_length=80)),
                ('y_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
